### ISSUE TITLE
Figures are stretched

### ISSUE THREAD

**Issue by ashinonyx** [mattwarkentin/torontodown#11]
My figures appear to be stretched to fit the whitespace of the page:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/47442853/215386070-b61764be-6929-4162-9efb-308d69a440ca.png">

This was generated using the markdown `![Growth curve for wild _Panthera tigris_]("figures/ch3/figure1.png"){width=90%}`, but seems to occur if I use `knitr::include_graphics` as well.

**Comment by mattwarkentin** [comment]
Is this figure produced by an R code chunk? The `width=90%` will control the width but will try to keep the aspect ratio from the saved picture (on disk). What code chunk options are used when producing this figure? You may want to specify the `fig.height` and `fig.width` of the figure so it has a known aspect ratio that you expect will behave with however you want the figure presented.

Let me know if this isn't along the right track.

**Comment by ashinonyx** [comment]
Yes, the figure is produced by the following R code chunk:

```{r ch3figure2, include = FALSE}
smuts_lions <- unnest(smuts_lions, data)

figure2 <- ggplot() +
  geom_point(aes(x = age, y = mass, col=sex), smuts_lions) +
  coord_cartesian(xlim = c(0, 10), ylim = c(0,300)) +
  stat_function(filter(smuts_lions, sex == "Female"), mapping = aes(x = age, col="Female"),
                fun = Richards, args = list(A = smuts_A$estimate[1], 
                                            K = smuts_K$estimate[1],
                                            I = smuts_I$estimate[1],
                                            m = 2),
                n = 1000, xlim = c(0, 15)) +
  stat_function(filter(smuts_lions, sex == "Male"), mapping = aes(x = age, col="Male"),
                fun = Richards, args = list(A = smuts_A$estimate[2], 
                                            K = smuts_K$estimate[2],
                                            I = smuts_K$estimate[2],
                                            m = 0),
                n = 1000, xlim = c(0,15))

ggsave("figure2.png", plot = figure2, device = "png", path = "figures/ch3/", width = 6, height = 4)
```

...which saves the following normally proportioned figure:

![figure2](https://user-images.githubusercontent.com/47442853/215569666-c4b9d4d1-6993-4297-ac78-2d3ce0d9bae2.png)

After playing around a bit more I've found that if I use `knitr::include_graphics` with the code chunk option `out.width="90%"` I get a normal figure. So, that's good! But then I run into issues with rendering italics in the caption (see #10 )
